#include <windows.h>
#include <fstream>
#include <string>
#include <thread>
#include <chrono>
#include <sstream>
#include <vector>
#include <mutex>
#include <queue>
#include <condition_variable>

HWND g_hEdit = nullptr;
HWND g_hWnd = nullptr;
std::string g_filename;
std::thread g_tailThread;
std::thread g_uiUpdateThread;
bool g_running = true;

std::queue<std::string> g_lineQueue;
std::mutex g_queueMutex;
std::condition_variable g_queueCV;

// Settings by default
int g_windowWidth = 800;
int g_windowHeight = 600;
int g_windowPosX = CW_USEDEFAULT;
int g_windowPosY = CW_USEDEFAULT;

// Font settings
std::string g_fontName = "Consolas";
int g_fontSize = 16;
int g_fontWeight = FW_NORMAL;
HFONT g_hFont = nullptr;

const int UI_UPDATE_INTERVAL_MS = 100;

// Functions Definitions
static std::wstring Utf8ToWide(const std::string& utf8);
static bool IsValidUtf8(const std::string& str);

// Read config.ini
static void LoadConfig() {
    std::ifstream config("config.ini");
    if (!config.is_open()) return;

    std::string line;
    while (std::getline(config, line)) {
        if (line.empty() || line[0] == ';' || line[0] == '#') continue;

        size_t start = line.find_first_not_of(" \t");
        if (start == std::string::npos) continue;
        size_t end = line.find_last_not_of(" \t");
        line = line.substr(start, end - start + 1);

        size_t eqPos = line.find('=');
        if (eqPos == std::string::npos) continue;

        std::string key = line.substr(0, eqPos);
        std::string value = line.substr(eqPos + 1);

        key.erase(0, key.find_first_not_of(" \t"));
        key.erase(key.find_last_not_of(" \t") + 1);
        value.erase(0, value.find_first_not_of(" \t"));
        value.erase(value.find_last_not_of(" \t") + 1);

        // Window size
        if (key == "Width" || key == "width") {
            g_windowWidth = std::stoi(value);
            if (g_windowWidth < 400) g_windowWidth = 400;
            if (g_windowWidth > 3840) g_windowWidth = 3840;
        }
        else if (key == "Height" || key == "height") {
            g_windowHeight = std::stoi(value);
            if (g_windowHeight < 300) g_windowHeight = 300;
            if (g_windowHeight > 2160) g_windowHeight = 2160;
        }
        else if (key == "PosX" || key == "posx") {
            g_windowPosX = std::stoi(value);
        }
        else if (key == "PosY" || key == "posy") {
            g_windowPosY = std::stoi(value);
        }
        // Font settings
        else if (key == "FontName" || key == "fontname" || key == "Font") {
            g_fontName = value;
        }
        else if (key == "FontSize" || key == "fontsize" || key == "Size") {
            g_fontSize = std::stoi(value);
            if (g_fontSize < 8) g_fontSize = 8;
            if (g_fontSize > 72) g_fontSize = 72;
        }
        else if (key == "FontWeight" || key == "fontweight" || key == "Weight") {
            g_fontWeight = std::stoi(value);
            // Normalize font weight
            if (g_fontWeight < 0) g_fontWeight = FW_NORMAL;
            if (g_fontWeight > 1000) g_fontWeight = FW_NORMAL;
        }
    }
}

// Save config.ini
static void SaveConfig() {
    std::ofstream config("config.ini");
    if (!config.is_open()) return;

    config << "; 'Tail -f Window' Configuration\n";
    config << "; Auto-generated by 'Tail -f Window' application\n";
    config << "; Modify these values to change window behavior\n\n";

    config << "# Window settings\n";
    config << "# Window size (min: 400x300, max: 3840x2160)\n";
    config << "Width = " << g_windowWidth << "\n";
    config << "Height = " << g_windowHeight << "\n\n";

    config << "# Window position (use -1 for default/CW_USEDEFAULT)\n";
    config << "PosX = " << g_windowPosX << "\n";
    config << "PosY = " << g_windowPosY << "\n\n";

    config << "# Font settings\n";
    config << "# Font name (examples: Consolas, Courier New, Lucida Console, MS Gothic)\n";
    config << "FontName = " << g_fontName << "\n\n";

    config << "# Font size in points (min: 8, max: 72)\n";
    config << "FontSize = " << g_fontSize << "\n\n";

    config << "# Font weight (100-900, where 400=Normal, 700=Bold)\n";
    config << "# 100=Thin, 200=ExtraLight, 300=Light, 400=Normal\n";
    config << "# 500=Medium, 600=SemiBold, 700=Bold, 800=ExtraBold, 900=Black\n";
    config << "FontWeight = " << g_fontWeight << "\n";
}

static HFONT CreateConfiguredFont() {
    std::wstring wideFontName = Utf8ToWide(g_fontName);

    LOGFONTW lf = { 0 };
    lf.lfHeight = -MulDiv(g_fontSize, GetDeviceCaps(GetDC(NULL), LOGPIXELSY), 72);
    lf.lfWidth = 0;
    lf.lfEscapement = 0;
    lf.lfOrientation = 0;
    lf.lfWeight = g_fontWeight;
    lf.lfItalic = FALSE;
    lf.lfUnderline = FALSE;
    lf.lfStrikeOut = FALSE;
    lf.lfCharSet = DEFAULT_CHARSET;
    lf.lfOutPrecision = OUT_DEFAULT_PRECIS;
    lf.lfClipPrecision = CLIP_DEFAULT_PRECIS;
    lf.lfQuality = DEFAULT_QUALITY;
    lf.lfPitchAndFamily = FIXED_PITCH | FF_MODERN;
    wcscpy_s(lf.lfFaceName, wideFontName.c_str());

    return CreateFontIndirectW(&lf);
}

// Проверка валидности UTF-8
static bool IsValidUtf8(const std::string& str) {
    if (str.empty()) return true;
    
    int expectedBytes = 0;
    for (unsigned char c : str) {
        if (expectedBytes == 0) {
            if ((c & 0x80) == 0) continue;
            else if ((c & 0xE0) == 0xC0) expectedBytes = 1;
            else if ((c & 0xF0) == 0xE0) expectedBytes = 2;
            else if ((c & 0xF8) == 0xF0) expectedBytes = 3;
            else return false;
        } else {
            if ((c & 0xC0) != 0x80) return false;
            expectedBytes--;
        }
    }
    return expectedBytes == 0;
}

static std::wstring Utf8ToWide(const std::string& utf8) {
    if (utf8.empty()) return L"";
    
    if (!IsValidUtf8(utf8)) {
        int wideSize = MultiByteToWideChar(CP_ACP, 0, utf8.c_str(), -1, NULL, 0);
        if (wideSize > 0) {
            std::wstring wide(wideSize - 1, 0);
            MultiByteToWideChar(CP_ACP, 0, utf8.c_str(), -1, &wide[0], wideSize);
            return wide;
        }
        return L"[Invalid encoding]";
    }
    
    int wideSize = MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, NULL, 0);
    if (wideSize == 0) {
        return L"[Conversion error]";
    }
    
    std::wstring wide(wideSize - 1, 0);
    MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, &wide[0], wideSize);
    return wide;
}

static void AddTextToWindowInternal(const std::string& text) {
    if (!g_hEdit) return;
    
    std::wstring wideText = Utf8ToWide(text);
    int textLength = GetWindowTextLengthW(g_hEdit);
    
    if (textLength > 10 * 1024 * 1024) { // 10 MB
        SendMessageW(g_hEdit, EM_SETSEL, 0, 1024 * 1024);
        SendMessageW(g_hEdit, EM_REPLACESEL, FALSE, (LPARAM)L"");
        textLength = GetWindowTextLengthW(g_hEdit);
    }
    
    SendMessageW(g_hEdit, EM_SETSEL, textLength, textLength);
    SendMessageW(g_hEdit, EM_REPLACESEL, FALSE, (LPARAM)(wideText + L"\r\n").c_str());
    SendMessageW(g_hEdit, EM_SCROLLCARET, 0, 0);
}

static void QueueLineForUI(const std::string& line) {
    if (line.empty()) return;
    
    {
        std::lock_guard<std::mutex> lock(g_queueMutex);
        g_lineQueue.push(line);
    }
    g_queueCV.notify_one();
}

static void UIUpdateThread() {
    while (g_running) {
        std::vector<std::string> linesToProcess;
        
        {
            std::unique_lock<std::mutex> lock(g_queueMutex);
            g_queueCV.wait_for(lock, std::chrono::milliseconds(UI_UPDATE_INTERVAL_MS), [] {
                return !g_lineQueue.empty() || !g_running;
            });
            
            if (!g_running) break;
            
            while (!g_lineQueue.empty()) {
                linesToProcess.push_back(g_lineQueue.front());
                g_lineQueue.pop();
            }
        }
        
        if (!linesToProcess.empty()) {
            for (const auto& line : linesToProcess) {
                AddTextToWindowInternal(line);
            }
        }
    }
}

static void TailFileThread() {
    std::ifstream file;
    std::streampos lastPos = 0;
    std::string incompleteLine;
    int errorCount = 0;
    const int MAX_ERRORS = 5;
    std::string utf8Buffer;
    
  //  QueueLineForUI("[Started monitoring file: " + g_filename + "]");
    
    while (g_running) {
        try {
            WIN32_FILE_ATTRIBUTE_DATA fileInfo;
            if (!GetFileAttributesExA(g_filename.c_str(), GetFileExInfoStandard, &fileInfo)) {
                if (file.is_open()) {
                    file.close();
                    QueueLineForUI("[File deleted? Waiting...]");
                }
                std::this_thread::sleep_for(std::chrono::milliseconds(500));
                lastPos = 0;
                incompleteLine.clear();
                utf8Buffer.clear();
                continue;
            }
            
            LARGE_INTEGER size{};
            size.HighPart = fileInfo.nFileSizeHigh;
            size.LowPart = fileInfo.nFileSizeLow;
            long long currentSize = size.QuadPart;

            if (!file.is_open()) {
                file.open(g_filename, std::ios::binary);
                if (!file.is_open()) {
                    std::this_thread::sleep_for(std::chrono::milliseconds(100));
                    continue;
                }
                
                if (lastPos > currentSize) {
                    QueueLineForUI("[File truncated or recreated]");
                    lastPos = 0;
                    incompleteLine.clear();
                    utf8Buffer.clear();
                }
                
                file.seekg(lastPos);
                if (file.fail()) {
                    file.clear();
                    lastPos = 0;
                    file.seekg(0);
                }
                errorCount = 0;
            }
            
            if (currentSize < lastPos) {
                QueueLineForUI("[File truncated]");
                file.close();
                lastPos = 0;
                incompleteLine.clear();
                utf8Buffer.clear();
                continue;
            }
            
            const long long CHUNK_SIZE = 65536; // 64 KB
            long long bytesToRead = currentSize - lastPos;
            
            if (bytesToRead <= 0) {
                std::this_thread::sleep_for(std::chrono::milliseconds(100));
                continue;
            }
            
            if (bytesToRead > CHUNK_SIZE) {
                bytesToRead = CHUNK_SIZE;
            }
            
            std::vector<char> buffer(bytesToRead);
            file.read(buffer.data(), bytesToRead);
            std::streamsize bytesRead = file.gcount();
            
            if (bytesRead > 0) {
                for (std::streamsize i = 0; i < bytesRead; ++i) {
                    char c = buffer[i];
                    
                    if (c == '\r') {
                        continue;
                    }
                    
                    if (c == '\n') {
                        if (!incompleteLine.empty()) {
                            QueueLineForUI(incompleteLine);
                            incompleteLine.clear();
                        } else {
                            QueueLineForUI("");
                        }
                        utf8Buffer.clear();
                    } else {
                        incompleteLine += c;
                        
                        if (!incompleteLine.empty()) {
                            unsigned char lastByte = incompleteLine.back();
                            if ((lastByte & 0xC0) == 0x80) {
                                utf8Buffer += c;
                            } else {
                                utf8Buffer.clear();
                            }
                        }
                    }
                }
                
                lastPos += bytesRead;
                
                if (file.fail() && !file.eof()) {
                    file.clear();
                    std::streampos actualPos = file.tellg();
                    if (actualPos != std::streampos(-1)) {
                        lastPos = actualPos;
                    }
                }
                
                errorCount = 0;
            } else {
                errorCount++;
                if (errorCount > MAX_ERRORS) {
                    QueueLineForUI("[Error: Unable to read file, retrying...]");
                    file.close();
                    errorCount = 0;
                }
                file.clear();
            }
            
            std::this_thread::sleep_for(std::chrono::milliseconds(50));
            
        } catch (const std::exception& e) {
            QueueLineForUI("[Exception: " + std::string(e.what()) + "]");
            errorCount++;
            if (errorCount > MAX_ERRORS) {
                file.close();
                errorCount = 0;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(500));
        } catch (...) {
            QueueLineForUI("[Unknown exception occurred]");
            errorCount++;
            if (errorCount > MAX_ERRORS) {
                file.close();
                errorCount = 0;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(500));
        }
    }
    
    if (!incompleteLine.empty()) {
        QueueLineForUI(incompleteLine);
    }
    // QueueLineForUI("[Monitoring stopped]");
}

static LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam) {
    switch (message) {
    case WM_CREATE:
    {
        g_hEdit = CreateWindowExW(
            WS_EX_CLIENTEDGE,
            L"EDIT",
            L"",
            WS_CHILD | WS_VISIBLE | ES_MULTILINE | ES_READONLY | WS_VSCROLL | WS_HSCROLL | ES_AUTOVSCROLL | ES_AUTOHSCROLL,
            0, 0, 0, 0,
            hWnd,
            NULL,
            GetModuleHandleW(NULL),
            NULL
        );
        
        SendMessageW(g_hEdit, EM_LIMITTEXT, 0, 0);
        
        g_hFont = CreateConfiguredFont();
        if (g_hFont) {
            SendMessageW(g_hEdit, WM_SETFONT, (WPARAM)g_hFont, TRUE);
        }
        
        g_uiUpdateThread = std::thread(UIUpdateThread);
    }
    break;
    
    case WM_SIZE:
    {
        if (wParam != SIZE_MINIMIZED) {
            RECT rc;
            GetClientRect(hWnd, &rc);
            SetWindowPos(g_hEdit, NULL, 0, 0, rc.right, rc.bottom, SWP_NOZORDER);
            
            if (rc.right != g_windowWidth || rc.bottom != g_windowHeight) {
                g_windowWidth = rc.right;
                g_windowHeight = rc.bottom;
                SaveConfig();
            }
        }
    }
    break;
    
    case WM_MOVE:
    {
        if (!IsIconic(hWnd)) {
            RECT rc;
            GetWindowRect(hWnd, &rc);
            if (rc.left != g_windowPosX || rc.top != g_windowPosY) {
                g_windowPosX = rc.left;
                g_windowPosY = rc.top;
                SaveConfig();
            }
        }
    }
    break;
    
    case WM_CLOSE:
        g_running = false;
        g_queueCV.notify_all();
        DestroyWindow(hWnd);
        break;
        
    case WM_DESTROY:
        g_running = false;
        g_queueCV.notify_all();
        
        if (g_tailThread.joinable()) {
            g_tailThread.join();
        }
        if (g_uiUpdateThread.joinable()) {
            g_uiUpdateThread.join();
        }
        if (g_hFont) {
            DeleteObject(g_hFont);
        }
        PostQuitMessage(0);
        break;
        
    default:
        return DefWindowProcW(hWnd, message, wParam, lParam);
    }
    return 0;
}

int WINAPI WinMain(_In_ HINSTANCE hInstance, _In_opt_ HINSTANCE hPrevInstance, _In_ LPSTR lpCmdLine, _In_ int nCmdShow) {
    LoadConfig();
    
    std::string cmdLine = lpCmdLine;
    
    if (!cmdLine.empty() && cmdLine.front() == '"') {
        cmdLine = cmdLine.substr(1, cmdLine.length() - 2);
    }
    
    if (cmdLine.empty()) {
        MessageBoxW(NULL, L"Usage: tailfw.exe <filename>", L"Error", MB_OK | MB_ICONERROR);
        return 1;
    }
    
    g_filename = cmdLine;
    
    std::wstring wideFilename = Utf8ToWide(g_filename);
    std::wstring windowTitle = L"Tail -f (w) | " + wideFilename;
    
    const wchar_t CLASS_NAME[] = L"TailWindowClass";
    
    WNDCLASSEXW wc = {};
    wc.cbSize = sizeof(WNDCLASSEXW);
    wc.lpfnWndProc = WndProc;
    wc.hInstance = hInstance;
    wc.lpszClassName = CLASS_NAME;
    wc.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    
    RegisterClassExW(&wc);
    
    g_hWnd = CreateWindowExW(
        0,
        CLASS_NAME,
        windowTitle.c_str(),
        WS_OVERLAPPEDWINDOW | WS_VISIBLE,
        g_windowPosX, g_windowPosY, g_windowWidth, g_windowHeight,
        NULL,
        NULL,
        hInstance,
        NULL
    );
    
    if (!g_hWnd) {
        MessageBoxW(NULL, L"Failed to create window", L"Error", MB_OK | MB_ICONERROR);
        return 1;
    }
    
    ShowWindow(g_hWnd, nCmdShow);
    UpdateWindow(g_hWnd);
    
    g_tailThread = std::thread(TailFileThread);
    
    MSG msg = {};
    while (GetMessageW(&msg, NULL, 0, 0)) {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }
    
    return 0;
}
