#include <windows.h>
#include <fstream>
#include <string>
#include <thread>
#include <chrono>
#include <sstream>

HWND g_hEdit = nullptr;
HWND g_hWnd = nullptr;
std::string g_filename;
std::thread g_tailThread;
bool g_running = true;

// Settings by default
int g_windowWidth = 800;
int g_windowHeight = 600;
int g_windowPosX = CW_USEDEFAULT;
int g_windowPosY = CW_USEDEFAULT;

// Font settings
std::string g_fontName = "Consolas";
int g_fontSize = 16;
int g_fontWeight = FW_NORMAL;
HFONT g_hFont = nullptr;

// Functions Definitions
static std::wstring Utf8ToWide(const std::string& utf8);

// Read config.ini
static void LoadConfig() {
    std::ifstream config("config.ini");
    if (!config.is_open()) return;

    std::string line;
    while (std::getline(config, line)) {
        if (line.empty() || line[0] == ';' || line[0] == '#') continue;

        size_t start = line.find_first_not_of(" \t");
        if (start == std::string::npos) continue;
        size_t end = line.find_last_not_of(" \t");
        line = line.substr(start, end - start + 1);

        size_t eqPos = line.find('=');
        if (eqPos == std::string::npos) continue;

        std::string key = line.substr(0, eqPos);
        std::string value = line.substr(eqPos + 1);

        key.erase(0, key.find_first_not_of(" \t"));
        key.erase(key.find_last_not_of(" \t") + 1);
        value.erase(0, value.find_first_not_of(" \t"));
        value.erase(value.find_last_not_of(" \t") + 1);

        // Window size
        if (key == "Width" || key == "width") {
            g_windowWidth = std::stoi(value);
            if (g_windowWidth < 400) g_windowWidth = 400;
            if (g_windowWidth > 3840) g_windowWidth = 3840;
        }
        else if (key == "Height" || key == "height") {
            g_windowHeight = std::stoi(value);
            if (g_windowHeight < 300) g_windowHeight = 300;
            if (g_windowHeight > 2160) g_windowHeight = 2160;
        }
        else if (key == "PosX" || key == "posx") {
            g_windowPosX = std::stoi(value);
        }
        else if (key == "PosY" || key == "posy") {
            g_windowPosY = std::stoi(value);
        }
        // Font settings
        else if (key == "FontName" || key == "fontname" || key == "Font") {
            g_fontName = value;
        }
        else if (key == "FontSize" || key == "fontsize" || key == "Size") {
            g_fontSize = std::stoi(value);
            if (g_fontSize < 8) g_fontSize = 8;
            if (g_fontSize > 72) g_fontSize = 72;
        }
        else if (key == "FontWeight" || key == "fontweight" || key == "Weight") {
            g_fontWeight = std::stoi(value);
            // Normalize font weight
            if (g_fontWeight < 0) g_fontWeight = FW_NORMAL;
            if (g_fontWeight > 1000) g_fontWeight = FW_NORMAL;
        }
    }
}

// Save config.ini
static void SaveConfig() {
    std::ofstream config("config.ini");
    if (!config.is_open()) return;

    config << "; 'Tail -f Window' Configuration\n";
    config << "; Auto-generated by 'Tail -f Window' application\n";
    config << "; Modify these values to change window behavior\n\n";

    config << "# Window settings\n";
    config << "# Window size (min: 400x300, max: 3840x2160)\n";
    config << "Width = " << g_windowWidth << "\n";
    config << "Height = " << g_windowHeight << "\n\n";

    config << "# Window position (use -1 for default/CW_USEDEFAULT)\n";
    config << "PosX = " << g_windowPosX << "\n";
    config << "PosY = " << g_windowPosY << "\n\n";

    config << "# Font settings\n";
    config << "# Font name (examples: Consolas, Courier New, Lucida Console, MS Gothic)\n";
    config << "FontName = " << g_fontName << "\n\n";

    config << "# Font size in points (min: 8, max: 72)\n";
    config << "FontSize = " << g_fontSize << "\n\n";

    config << "# Font weight (100-900, where 400=Normal, 700=Bold)\n";
    config << "# 100=Thin, 200=ExtraLight, 300=Light, 400=Normal\n";
    config << "# 500=Medium, 600=SemiBold, 700=Bold, 800=ExtraBold, 900=Black\n";
    config << "FontWeight = " << g_fontWeight << "\n";
}

// Create font from settings
static HFONT CreateConfiguredFont() {
    std::wstring wideFontName = Utf8ToWide(g_fontName);

    LOGFONTW lf = { 0 };
    lf.lfHeight = -MulDiv(g_fontSize, GetDeviceCaps(GetDC(NULL), LOGPIXELSY), 72);
    lf.lfWidth = 0;
    lf.lfEscapement = 0;
    lf.lfOrientation = 0;
    lf.lfWeight = g_fontWeight;
    lf.lfItalic = FALSE;
    lf.lfUnderline = FALSE;
    lf.lfStrikeOut = FALSE;
    lf.lfCharSet = DEFAULT_CHARSET;
    lf.lfOutPrecision = OUT_DEFAULT_PRECIS;
    lf.lfClipPrecision = CLIP_DEFAULT_PRECIS;
    lf.lfQuality = DEFAULT_QUALITY;
    lf.lfPitchAndFamily = FIXED_PITCH | FF_MODERN;
    wcscpy_s(lf.lfFaceName, wideFontName.c_str());

    return CreateFontIndirectW(&lf);
}

static std::wstring Utf8ToWide(const std::string& utf8) {
    if (utf8.empty()) return L"";
    int wideSize = MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, NULL, 0);
    std::wstring wide(wideSize - 1, 0);
    MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, &wide[0], wideSize);
    return wide;
}

static void AddTextToWindow(const std::string& text) {
    if (g_hEdit) {
        std::wstring wideText = Utf8ToWide(text);
        int textLength = GetWindowTextLengthW(g_hEdit);
        SendMessageW(g_hEdit, EM_SETSEL, textLength, textLength);
        SendMessageW(g_hEdit, EM_REPLACESEL, FALSE, (LPARAM)(wideText + L"\r\n").c_str());
        SendMessageW(g_hEdit, EM_SCROLLCARET, 0, 0);
    }
}

static void TailFileThread() {
    std::ifstream file(g_filename, std::ios::binary);

    if (!file.is_open()) {
        AddTextToWindow("Cannot open file: " + g_filename);
        return;
    }

    file.seekg(0, std::ios::end);
    std::streampos lastPos = file.tellg();
    file.clear();

    while (g_running) {
        WIN32_FILE_ATTRIBUTE_DATA fileInfo;
        long long currentSize = 0;

        if (GetFileAttributesExA(g_filename.c_str(), GetFileExInfoStandard, &fileInfo)) {
            LARGE_INTEGER size{};
            size.HighPart = fileInfo.nFileSizeHigh;
            size.LowPart = fileInfo.nFileSizeLow;
            currentSize = size.QuadPart;
        }

        if (currentSize > lastPos) {
            file.close();
            file.open(g_filename, std::ios::binary);

            if (file.is_open()) {
                file.seekg(lastPos);
                file.clear();

                std::string newData;
                newData.resize(currentSize - lastPos);
                file.read(&newData[0], newData.size());

                std::string line;
                for (size_t i = 0; i < newData.size(); ++i) {
                    char c = newData[i];

                    if (c == '\r') {
                        continue;
                    }
                    else if (c == '\n') {
                        AddTextToWindow(line);
                        line.clear();
                    }
                    else {
                        line += c;
                    }
                }

                if (!line.empty()) {
                    AddTextToWindow(line);
                }

                lastPos = file.tellg();
                if (lastPos == -1) {
                    lastPos = currentSize;
                }

                file.clear();
            }
        }
        else if (currentSize < lastPos) {
            AddTextToWindow("[File truncated]");
            lastPos = 0;
        }

        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
}

static LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam) {
    switch (message) {
    case WM_CREATE:
    {
        g_hEdit = CreateWindowExW(
            WS_EX_CLIENTEDGE,
            L"EDIT",
            L"",
            WS_CHILD | WS_VISIBLE | ES_MULTILINE | ES_READONLY | WS_VSCROLL | WS_HSCROLL | ES_AUTOVSCROLL | ES_AUTOHSCROLL,
            0, 0, 0, 0,
            hWnd,
            NULL,
            GetModuleHandleW(NULL),
            NULL
        );

        // Create font from config settings
        g_hFont = CreateConfiguredFont();
        if (g_hFont) {
            SendMessageW(g_hEdit, WM_SETFONT, (WPARAM)g_hFont, TRUE);
        }
    }
    break;

    case WM_SIZE:
    {
        if (wParam != SIZE_MINIMIZED) {
            RECT rc;
            GetClientRect(hWnd, &rc);
            SetWindowPos(g_hEdit, NULL, 0, 0, rc.right, rc.bottom, SWP_NOZORDER);

            if (rc.right != g_windowWidth || rc.bottom != g_windowHeight) {
                g_windowWidth = rc.right;
                g_windowHeight = rc.bottom;
                SaveConfig();
            }
        }
    }
    break;

    case WM_MOVE:
    {
        if (!IsIconic(hWnd)) {
            RECT rc;
            GetWindowRect(hWnd, &rc);
            if (rc.left != g_windowPosX || rc.top != g_windowPosY) {
                g_windowPosX = rc.left;
                g_windowPosY = rc.top;
                SaveConfig();
            }
        }
    }
    break;

    case WM_DESTROY:
        g_running = false;
        if (g_tailThread.joinable()) {
            g_tailThread.join();
        }
        if (g_hFont) {
            DeleteObject(g_hFont);
        }
        PostQuitMessage(0);
        break;

    default:
        return DefWindowProcW(hWnd, message, wParam, lParam);
    }
    return 0;
}

int WINAPI WinMain(_In_ HINSTANCE hInstance, _In_opt_ HINSTANCE hPrevInstance, _In_ LPSTR lpCmdLine, _In_ int nCmdShow) {
    LoadConfig();

    std::string cmdLine = lpCmdLine;

    if (!cmdLine.empty() && cmdLine.front() == '"') {
        cmdLine = cmdLine.substr(1, cmdLine.length() - 2);
    }

    if (cmdLine.empty()) {
        MessageBoxW(NULL, L"Usage: tailfw.exe <filename>", L"Error", MB_OK | MB_ICONERROR);
        return 1;
    }

    g_filename = cmdLine;

    std::wstring wideFilename = Utf8ToWide(g_filename);
    std::wstring windowTitle = L"Tail -f (w) | " + wideFilename;

    const wchar_t CLASS_NAME[] = L"TailWindowClass";

    WNDCLASSEXW wc = {};
    wc.cbSize = sizeof(WNDCLASSEXW);
    wc.lpfnWndProc = WndProc;
    wc.hInstance = hInstance;
    wc.lpszClassName = CLASS_NAME;
    wc.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);

    RegisterClassExW(&wc);

    g_hWnd = CreateWindowExW(
        0,
        CLASS_NAME,
        windowTitle.c_str(),
        WS_OVERLAPPEDWINDOW | WS_VISIBLE,
        g_windowPosX, g_windowPosY, g_windowWidth, g_windowHeight,
        NULL,
        NULL,
        hInstance,
        NULL
    );

    if (!g_hWnd) {
        MessageBoxW(NULL, L"Failed to create window", L"Error", MB_OK | MB_ICONERROR);
        return 1;
    }

    ShowWindow(g_hWnd, nCmdShow);
    UpdateWindow(g_hWnd);

    g_tailThread = std::thread(TailFileThread);

    MSG msg = {};
    while (GetMessageW(&msg, NULL, 0, 0)) {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }

    return 0;
}